require 'allowing/validations/presence_validation'
require 'allowing/validations/format_validation'
require 'allowing/validations/size_validation'
require 'allowing/validations/inclusion_validation'
require 'allowing/validations/exclusion_validation'
require 'allowing/validations/with_validation'
